name: LaTeX compilation
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FILE_NAME: main
    steps:
      - name: set date tag
        run: echo "NOW=$(date '+%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file:
            ${{env.FILE_NAME}}.tex
          args:
            -pdfdvi
      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "${{ env.NOW }}"
          prerelease: false
          title: "${{ env.NOW }}"
          files: |
            ${{env.FILE_NAME}}.pdf
