name: Lint
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: "22.x"
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Run lint
        run: |
          npm install
          npm run lint
      # ↑のステップでtextlintが違反を検知した場合のみ実行
      - name: Run reviewdog
        if: failure()
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run --silent lint-style | reviewdog -f=checkstyle -name="textlint" -diff="Git diff HEAD^" -reporter=github-check
